import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Luckiest_Guy } from 'next/font/google';

const inter = Luckiest_Guy({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
